In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
df = pd.read_csv("g43_Space_Missions_v2.csv", sep=';', encoding='latin1', parse_dates=['transaction_date', 'created_date'], dayfirst=True)

In [ ]:
df_agency = df.loc[:, ['agency_id', 'agency_name']]
df_agency = df_agency.drop_duplicates(subset='agency_id', keep='first').copy()
df_agency.rename(columns={'agency_id': 'id', 'agency_name': 'name'}, inplace=True)

    id                        name
0  162                 Soto-Garcia
1  497               Andrews-Lopez
2  177  Taylor, Rivera and Freeman

In [ ]:
df_mission = df.loc[:, ['mission_id', 'mission_title', 'mission_category', 'created_date']]
df_mission = df_mission.drop_duplicates(subset='mission_id', keep='first').copy()
df_mission.rename(columns={'mission_id': 'id', 'mission_title': 'name', 'mission_category': 'mission_type', 'created_date': 'start_date'}, inplace=True)

    id                 name             mission_type start_date
0   39  Project Horizon-173     Colonização de Marte 2021-03-02
1  212   Nebula 292 Orbiter     Pesquisa Astrofísica 2021-07-20
2  380     Viking 538 Phase  Mineração de Asteroides 2025-12-21

In [ ]:
df_astronaut = df.loc[:, ['astronaut_id', 'astronaut_info', 'agency_id']]
df_astronaut = df_astronaut.dropna(subset=['astronaut_id']).copy()
df_astronaut = df_astronaut.drop_duplicates(subset='astronaut_id', keep='first')
df_astronaut.rename(columns={'astronaut_id': 'id', 'astronaut_info': 'name'}, inplace=True)

      id            name  agency_id
1  199.0  Dmitry F. Duke        497
2   25.0  Aiko X. Ivanov        177
7   60.0   Sonia B. Wang        222

In [ ]:
df_agencymission = df.loc[:, ['agency_id', 'mission_id', 'transaction_date', 'amount']]
df_agencymission = df_agencymission.dropna(subset=['transaction_date', 'amount']).copy()
df_agencymission = df_agencymission.drop_duplicates(subset=['agency_id', 'mission_id', 'transaction_date'], keep='first')

   agency_id  mission_id transaction_date  amount
0        162          39       2021-08-04    4705
1        497         212       2024-06-20    1752
2        177         380       2022-10-28    4702

In [ ]:
engine = create_engine('sqlite:///data/space_missions.db')

In [ ]:
df_agency.to_sql('Agency', con=engine, if_exists='replace', index=False)
df_mission.to_sql('Mission', con=engine, if_exists='replace', index=False)
df_astronaut.to_sql('Astronaut', con=engine, if_exists='replace', index=False)
df_agencymission.to_sql('AgencyMission', con=engine, if_exists='replace', index=False)

9999

In [ ]:
result = pd.read_sql('AgencyMission', con=engine)

   agency_id  mission_id transaction_date  amount
0        162          39       2021-08-04    4705
1        497         212       2024-06-20    1752
2        177         380       2022-10-28    4702

In [ ]:
engine.dispose()